spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: test
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat,wall
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.fengfeng.druid.entry

server:
  port: 8088
logging:
  level:
    com:
      fengfeng:
        druid:
          mapper: debug